// PROTOTYPE — realistic dictated Captures, each probing one rule.
// `count` is the expected number of Tasks; `want` says what a good answer looks like.

export const CAPTURES = [
  { id: "three-mixed", probe: "Basic split + deadline",
    text: "Email Sarah the invoice and also I need to refactor the auth module before Friday, oh and buy milk",
    count: 3, want: "Email Sarah the invoice / Refactor the auth module (Details: before Fri 9 Oct, High) / Buy milk (Low, Quick)" },
  { id: "decide", probe: "Thinking counts as a Task",
    text: "think about whether we should move to Postgres",
    count: 1, want: "Decide whether to move to Postgres; Long or Short, Medium" },
  { id: "call-mom", probe: "Smallest possible Capture",
    text: "Call mom",
    count: 1, want: "Call mom, Quick, Details empty" },
  { id: "self-correction", probe: "Spoken correction wins",
    text: "Book a dentist appointment for Tuesday, no actually Thursday, and remind Ahmed about the design review.",
    count: 2, want: "Dentist on Thursday (not Tuesday) in Title or Details; Remind Ahmed about the design review" },
  { id: "one-errand", probe: "Several objects, one action",
    text: "Pick up milk, eggs, bread and some coffee on the way home.",
    count: 1, want: "One Task: Pick up milk, eggs, bread and coffee" },
  { id: "chatter", probe: "Nothing actionable → zero Tasks",
    text: "Ugh, today was so long. The standup ran over again and I'm honestly exhausted.",
    count: 0, want: "Empty list" },
  { id: "fact", probe: "A fact with no ask → zero Tasks",
    text: "The office wifi password is written on the back of the fridge.",
    count: 0, want: "Empty list (debatable: some would want 'Note the wifi password')" },
  { id: "steps-said", probe: "User lists steps of one job",
    text: "I need to set up the CI pipeline for the widget repo, so that's writing the GitHub workflow, adding the ARM64 build and sorting out the signing certificate",
    count: 1, want: "Glossary says one Task; the steps the user said go in Details. Debatable: signing cert could stand alone" },
  { id: "urgent", probe: "Explicit urgency word",
    text: "Urgent, the production cert expires tonight, renew it",
    count: 1, want: "Renew the production cert; High; Details: expires tonight (Wed 7 Oct)" },
  { id: "no-rush", probe: "Explicit low urgency",
    text: "Someday I'd like to properly learn Rust, no rush at all",
    count: 1, want: "Learn Rust; Low; Long" },
  { id: "someone-waiting", probe: "Someone waiting → High",
    text: "Bilal has been waiting on my code review for two days now, I really need to get to that",
    count: 1, want: "Review Bilal's code; High; Short; Details: waiting two days" },
  { id: "roman-urdu", probe: "Language of the Capture",
    text: "Ammi ko call karna hai aur bijli ka bill kal tak pay karna hai",
    count: 2, want: "Titles in Roman Urdu, e.g. 'Ammi ko call karna' / 'Bijli ka bill pay karna'; bill High with 'by Thu 8 Oct'" },
  { id: "self-question", probe: "Question to self → check Task",
    text: "Did I ever send the signed lease back to the landlord? Check that.",
    count: 1, want: "Check whether I sent the signed lease to the landlord; Quick" },
  { id: "two-channels", probe: "Same action, two places",
    text: "Write the release notes for 0.3 and then post them on Discord and on Twitter",
    count: 2, want: "Write the release notes for 0.3 / Post them on Discord and Twitter (one Task, not two)" },
  { id: "meeting", probe: "Calendar event vs. prep",
    text: "Meeting with Hina on Monday at 3 to go over the Q4 budget, I need to prep the slides before that",
    count: 1, want: "Prep the Q4 budget slides; Details: for meeting with Hina Mon 12 Oct 3pm. The meeting itself is not a Task (debatable)" },
  { id: "meeting-only", probe: "Meeting with nothing to prep",
    text: "Dinner with Asad and Mahnoor on Saturday at 8",
    count: 1, want: "Attend dinner with Asad and Mahnoor; Details: Sat 10 Oct at 8" },
  { id: "long-title", probe: "60-char Title limit",
    text: "Reply to the email from the university admissions office asking for my transcript and the two recommendation letters",
    count: 1, want: "Title ≤60 chars, e.g. 'Reply to the admissions office email'; transcript + letters in Details" },
  { id: "ramble", probe: "Long dictation, many items",
    text: "Okay so a bunch of stuff. First the landlord said the plumber's coming tomorrow morning so I have to be home before nine. Um, I should finally cancel that Adobe subscription, it renews on the fifteenth. Zain asked me to send him the API docs, he's blocked on it. And at some point look into whether the widget can use less memory when it's docked. Oh and I need to buy a birthday gift for Fatima, her birthday is next Saturday.",
    count: 5, want: "Be home before 9 for the plumber (High, Thu 8 Oct) / Cancel Adobe subscription (renews 15 Oct) / Send Zain the API docs (High, blocked) / Look into lower docked memory (Low/Medium, Long) / Buy Fatima a birthday gift (Sat 17 Oct)" },
  { id: "misheard", probe: "Transcription slip (Re-interpret material)",
    text: "Email Sara the in voice for the Q3 retainer and cc Omar",
    count: 1, want: "Keep the user's words; a light fix to 'invoice' is fine. Details: Q3 retainer, cc Omar" },
];
